### ISSUE TITLE
Website blocker

### ISSUE THREAD

**Issue by geek-atif** [Gaurav-Punjabi/app-blocker#1]
This is not a bug. want to know how to create a website blocker. how it works ?

**Comment by abinpaul1** [comment]
> This is not a bug. want to know how to create a website blocker. how it works ?

I can think of two ways.
1. You could create a VPN service to act as a custom DNS server. Then you can point the websites to localhost and thereby block them. 
Refer here
<a>https://github.com/IngoZenz/personaldnsfilter</a>
2. Secondly if you are on Chrome, you could use the `setApplicationRestrictions` from the `DevicePolicyManager` to block sites on Chrome. However that would require you to have `Device-Owner` Priviliges.

The first one would be better suited for a production level app.

**Comment by geek-atif** [comment]
> > This is not a bug. want to know how to create a website blocker. how it works ?
> 
> I can think of two ways.
> 
> 1. You could create a VPN service to act as a custom DNS server. Then you can point the websites to localhost and thereby block them.
>    Refer here
>    https://github.com/IngoZenz/personaldnsfilter
> 2. Secondly if you are on Chrome, you could use the `setApplicationRestrictions` from the `DevicePolicyManager` to block sites on Chrome. However that would require you to have `Device-Owner` Priviliges.
> 
> The first one would be better suited for a production level app.

Thank you so much for you reply. I have Device-Owner Privileges . I will check both ways.
